# Generated by Django 3.2.25 on 2026-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tombo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField()),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
