# Generated by Django 4.2.11 on 2026-01-29 03:26

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('funcao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(default='Capanema', max_length=100)),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nome_patrimonio', models.CharField(max_length=200)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('custo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado'), ('manutencao', 'Manutenção'), ('perdido', 'Perdido'), ('descartado', 'Descartado')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.categoriapatrimonio')),
                ('colaborador_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.colaborador')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.localizacao')),
            ],
        ),
    ]
