# Generated by Django 4.2.11 on 2026-01-31 12:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('secretaria', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutenção'), ('descartado', 'Descartado')], default='ativo', max_length=20)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='localizacao',
            name='gerente',
        ),
        migrations.DeleteModel(
            name='BemPatrimonial',
        ),
        migrations.DeleteModel(
            name='CategoriaPatrimonio',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
