# Generated by Django 3.2.25 on 2026-01-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_alter_bempatrimonial_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
