# Generated by Django 4.2.11 on 2026-01-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_patrimonio_remove_localizacao_gerente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='patrimonios/'),
        ),
    ]
