# Generated by Django 3.2.25 on 2026-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_alter_bempatrimonial_data_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='secretaria',
            field=models.CharField(blank=True, choices=[('admin', 'Secretaria Administração'), ('financas', 'Secretaria Finanças'), ('educacao', 'Secretaria Educação'), ('saude', 'Secretaria Saúde'), ('obras', 'Secretaria Obras'), ('patrimonio', 'Departamento Patrimônio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
