# Generated by Django 3.2.25 on 2026-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_auto_20260126_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='departamento',
            field=models.CharField(blank=True, choices=[('admin', 'Administração'), ('financas', 'Finanças'), ('educacao', 'Educação'), ('saude', 'Saúde'), ('obras', 'Obras'), ('meio_ambiente', 'Meio Ambiente'), ('cultura', 'Cultura')], max_length=20),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='gerente_patrimonio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='numero_nf',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
