# Generated by Django 3.2.25 on 2026-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_auto_20260126_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bempatrimonial',
            old_name='localizacao',
            new_name='localizacao_accent',
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
