# Generated by Django 3.2.25 on 2026-01-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_auto_20260126_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bempatrimonial',
            old_name='localizacao_accent',
            new_name='localizacao',
        ),
    ]
