# Generated by Django 3.2.25 on 2026-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0007_rename_localizacao_accent_bempatrimonial_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('admin', 'Secretaria Administração'), ('financas', 'Secretaria Finanças'), ('educacao', 'Secretaria Educação'), ('saude', 'Secretaria Saúde'), ('obras', 'Secretaria Obras'), ('patrimonio', 'Departamento Patrimônio')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
