# Generated by Django 4.2.11 on 2026-01-27 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0008_alter_bempatrimonial_localizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bempatrimonial',
            options={'ordering': ['numero_tombo'], 'verbose_name': 'Bem Patrimonial', 'verbose_name_plural': 'Bens Patrimoniais'},
        ),
        migrations.RenameField(
            model_name='bempatrimonial',
            old_name='gerente_patrimonio',
            new_name='gerente_responsavel',
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='patrimonio/'),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='nome_patrimonio',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Manutenção'), ('baixa', 'Baixa'), ('inexistente', 'Inexistente')], default='disponivel', max_length=30),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_tombo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='secretaria',
            field=models.CharField(choices=[('administracao', 'Administração'), ('financas', 'Finanças'), ('educacao', 'Educação'), ('saude', 'Saúde'), ('obras', 'Obras'), ('patrimonio', 'Patrimônio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
